# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "teds-accounts"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "teds-accounts-db"
database_id = "43e32e93-2ddc-477a-9037-3799c4376d66"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "f4168fcc34804e9fbb7ae8309c7d64ce"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "teds-accounts-files"


# To protect the database id, kv id, r2 bucket name, we ignore this
# file when committing to the repo by running once:
# git update-index --assume-unchanged wrangler.toml
#
# Put back in git if you need to commit this file:
# git update-index --no-assume-unchanged wrangler.toml